// Loads manifest.json (generated by tools/build-manifest.mjs) and every asset
// it lists. If manifest.json is missing (e.g. fresh checkout, no assets yet),
// falls back to an empty list and the game draws procedural placeholders.
// Collectibles fall back to built-in spinning 8-bit coins; sounds fall back
// to synthesized chiptune in sfx.js.

import { createBuiltinCoins } from "./coins.js";

function loadImage(src) {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null);
    img.src = src;
  });
}

function loadAudio(src) {
  if (!src) return null;
  const audio = new Audio(src);
  audio.preload = "auto";
  return audio;
}

async function fetchManifest() {
  try {
    const res = await fetch("manifest.json", { cache: "no-store" });
    if (!res.ok) throw new Error("no manifest");
    return await res.json();
  } catch {
    return {
      birds: [],
      collectibles: [],
      backgrounds: [],
      defaultBackground: null,
      ui: {},
      audio: {},
    };
  }
}

export async function loadAssets() {
  const manifest = await fetchManifest();
  const birdDefs = manifest.birds && manifest.birds.length
    ? manifest.birds
    : (manifest.bird || []).map((file) => ({
        id: file,
        file,
        label: file.split("/").pop().replace(/\.[^.]+$/, "").toUpperCase(),
      }));

  const [birdImages, collectibleImages, backgroundImages, titleImg, pipeBodyImg, pipeCapImg, groundImg] =
    await Promise.all([
      Promise.all(birdDefs.map((b) => loadImage(b.file))),
      Promise.all((manifest.collectibles || []).map((c) => loadImage(c.file))),
      Promise.all((manifest.backgrounds || []).map(loadImage)),
      manifest.ui?.title ? loadImage(manifest.ui.title) : Promise.resolve(null),
      manifest.ui?.pipeBody ? loadImage(manifest.ui.pipeBody) : Promise.resolve(null),
      manifest.ui?.pipeCap ? loadImage(manifest.ui.pipeCap) : Promise.resolve(null),
      manifest.ui?.ground ? loadImage(manifest.ui.ground) : Promise.resolve(null),
    ]);

  // Each skin is one static picture (no more multi-frame flap animation art).
  const birds = birdDefs
    .map((b, i) => ({ id: b.id, label: b.label, image: birdImages[i] }))
    .filter((b) => b.image);

  let collectibles = (manifest.collectibles || [])
    .map((c, i) => ({ ...c, image: collectibleImages[i] }))
    .filter((c) => c.image);
  if (collectibles.length === 0) {
    collectibles = createBuiltinCoins();
  }

  const defaultIndex = (manifest.backgrounds || []).findIndex(
    (b) => b === manifest.defaultBackground
  );
  const backgrounds = (manifest.backgrounds || [])
    .map((src, i) => ({ src, image: backgroundImages[i] }))
    .filter((b) => b.image);
  // Move default background to the front so it's used at score 0.
  if (defaultIndex >= 0) {
    const idx = backgrounds.findIndex((b) => b.src === manifest.defaultBackground);
    if (idx > 0) {
      const [def] = backgrounds.splice(idx, 1);
      backgrounds.unshift(def);
    }
  }

  const sounds = {
    flap: loadAudio(manifest.audio?.flap),
    point: loadAudio(manifest.audio?.point),
    collect: loadAudio(manifest.audio?.collect),
    hit: loadAudio(manifest.audio?.hit),
    ui: loadAudio(manifest.audio?.ui),
  };

  return {
    birds,
    collectibles,
    backgrounds,
    title: titleImg,
    pipeBody: pipeBodyImg,
    pipeCap: pipeCapImg,
    ground: groundImg,
    sounds,
  };
}
