// Loads manifest.json (generated by tools/build-manifest.mjs) and every asset
// it lists. If manifest.json is missing (e.g. fresh checkout, no assets yet),
// falls back to an empty list and the game draws procedural placeholders.

function loadImage(src) {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null);
    img.src = src;
  });
}

function loadAudio(src) {
  if (!src) return null;
  const audio = new Audio(src);
  audio.preload = "auto";
  return audio;
}

async function fetchManifest() {
  try {
    const res = await fetch("manifest.json", { cache: "no-store" });
    if (!res.ok) throw new Error("no manifest");
    return await res.json();
  } catch {
    return {
      bird: [],
      collectibles: [],
      backgrounds: [],
      defaultBackground: null,
      ui: {},
      audio: {},
    };
  }
}

export async function loadAssets() {
  const manifest = await fetchManifest();

  const [birdFrames, collectibleImages, backgroundImages, titleImg, pipeBodyImg, pipeCapImg, groundImg] =
    await Promise.all([
      Promise.all((manifest.bird || []).map(loadImage)),
      Promise.all((manifest.collectibles || []).map((c) => loadImage(c.file))),
      Promise.all((manifest.backgrounds || []).map(loadImage)),
      manifest.ui?.title ? loadImage(manifest.ui.title) : Promise.resolve(null),
      manifest.ui?.pipeBody ? loadImage(manifest.ui.pipeBody) : Promise.resolve(null),
      manifest.ui?.pipeCap ? loadImage(manifest.ui.pipeCap) : Promise.resolve(null),
      manifest.ui?.ground ? loadImage(manifest.ui.ground) : Promise.resolve(null),
    ]);

  const bird = birdFrames.filter(Boolean);

  const collectibles = (manifest.collectibles || [])
    .map((c, i) => ({ ...c, image: collectibleImages[i] }))
    .filter((c) => c.image);

  const defaultIndex = (manifest.backgrounds || []).findIndex(
    (b) => b === manifest.defaultBackground
  );
  const backgrounds = (manifest.backgrounds || [])
    .map((src, i) => ({ src, image: backgroundImages[i] }))
    .filter((b) => b.image);
  // Move default background to the front so it's used at score 0.
  if (defaultIndex >= 0) {
    const idx = backgrounds.findIndex((b) => b.src === manifest.defaultBackground);
    if (idx > 0) {
      const [def] = backgrounds.splice(idx, 1);
      backgrounds.unshift(def);
    }
  }

  const sounds = {
    flap: loadAudio(manifest.audio?.flap),
    point: loadAudio(manifest.audio?.point),
    collect: loadAudio(manifest.audio?.collect),
    hit: loadAudio(manifest.audio?.hit),
  };

  return {
    bird,
    collectibles,
    backgrounds,
    title: titleImg,
    pipeBody: pipeBodyImg,
    pipeCap: pipeCapImg,
    ground: groundImg,
    sounds,
  };
}

export function playSound(audio) {
  if (!audio) return;
  try {
    const clone = audio.cloneNode ? audio.cloneNode() : audio;
    clone.currentTime = 0;
    clone.volume = 1;
    const p = clone.play();
    if (p && p.catch) p.catch(() => {});
  } catch {
    // ignore playback errors (e.g. autoplay policy before first touch)
  }
}
